### ISSUE TITLE
Confused by docs

### ISSUE THREAD

**Issue by ronsavage** [frioux/Config-Station#1]
Your docs refer to env_var as 'a prefix for all the env vars'. But further down, each usage is as a suffix.

**Comment by ronsavage** [comment]
Sorry. I meant env_key.

**Comment by frioux** [comment]
I'll make some tweaks to clarify. Ultimately it's both, but prefix for
users in general.

## 

sent from a rotary phone, pardon my brevity

**Comment by frioux** [comment]
Ok, I fixed this by adding some extra docs.  Thanks for the note; let me know if
this doesn't clear it up enough.
